#!/bin/bash

source ../env.sh

CURRENT_DIR=$(pwd)
export ETHERFLOW_JRD_SIMULATION_PATH="$CURRENT_DIR/"
# 构建镜像
CMD_BUILD="docker build --build-arg  VERSION=${ETHERFLOW_JRD_VERSION} --build-arg REGISTRY=${ETHERFLOW_REGISTRY} --build-arg JRD_BASE_IMAGE=${ETHERFLOW_JRD_BASE_NOTEBOOK_IMAGE_NAME} --build-arg vncserver=${ETHERFLOW_VNCSERVER} -t $ETHERFLOW_JRD_SIMULATION_IMAGE_NAME -f $ETHERFLOW_JRD_SIMULATION_PATH/Dockerfile  $ETHERFLOW_JRD_SIMULATION_PATH"
echo $CMD_BUILD
$CMD_BUILD

# 标记镜像
CMD_TAG="docker tag $ETHERFLOW_JRD_SIMULATION_IMAGE_NAME $ETHERFLOW_REGISTRY/$ETHERFLOW_JRD_SIMULATION_IMAGE_NAME:$ETHERFLOW_JRD_VERSION"
echo $CMD_TAG
$CMD_TAG

# 推送镜像到私有仓库
CMD_PUSH="docker push $ETHERFLOW_REGISTRY/$ETHERFLOW_JRD_SIMULATION_IMAGE_NAME:$ETHERFLOW_JRD_VERSION"
echo $CMD_PUSH
$CMD_PUSH